### ISSUE TITLE
Confusing tutorial

### ISSUE THREAD

**Issue by Michael1993** [verhas/javageci#43]
In the first tutorial, there is this snippet:

```java
@Test
void testAccessor() throws Exception {
    Geci geci;
    Assertions.assertFalse(
            (geci = new Geci()).source(maven().module("javageci-examples").mainSource())
                    .register(Accessor.builder().build())
                    .generate(),
            geci.failed());
}
```

This is confusing because if you add the "required" dependencies (listed as)
 ```xml
 <dependency>
     <!-- This is optional, you can use your own annotations or comment config -->
     <groupId>com.javax0.geci</groupId>
     <artifactId>javageci-annotation</artifactId>
     <version>1.5.1-SNAPSHOT</version>
 </dependency>
 <dependency>
     <groupId>com.javax0.geci</groupId>
     <artifactId>javageci-engine</artifactId>
     <scope>test</scope>
     <version>1.5.1-SNAPSHOT</version>
 </dependency>
 ```
then trying to import Geci shows three possible choices:
* an interface
* a class
* an annotation

This is confusing a little or, at the very least, annoying. Does `Geci` really need to be an interface? Do we expect other people to provide new/additional implementations of this interface? If not, it warrants an investigation if it could be removed, replaced or renamed.

Another confusing thing is that `Accessor` can not be imported. It is part of the `javageci-core` artifact which `javageci-engine` does not require.
Either it should be used by `javageci-engine` or the bit `"There are other modules, but you do not need to declare dependency on them as the engine module has transitive dependency and thus maven automatically will use them."` has to be rewritten.

**Comment by verhas** [comment]
Go ahead with a pull request

- suggesting a different name for the interface
- new verbiage for the confusing sentence
